name: Release PDF (Korean Translation)

on:
  push:
    branches:
      - translate-book-to-korean
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Korean system fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-nanum fonts-noto-cjk

      - name: Compile LaTeX document
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          texlive_version: '2024'
          run: |
            xelatex -interaction=nonstopmode -halt-on-error book_ko.tex
            xelatex -interaction=nonstopmode -halt-on-error book_ko.tex

      - name: List workspace and check for PDF
        run: |
          echo "Listing files in workspace:"
          ls -la
          if [ ! -f book_ko.pdf ]; then
            echo "ERROR: book_ko.pdf not found after build"
            exit 1
          fi

      - name: Delete existing release & tag (if present)
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const tag = 'latest-korean-build'
            try {
              const releases = await github.rest.repos.listReleases({
                owner: context.repo.owner,
                repo: context.repo.repo,
              })
              for (const r of releases.data) {
                if (r.tag_name === tag) {
                  await github.rest.repos.deleteRelease({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    release_id: r.id,
                  })
                }
              }
              try {
                await github.rest.git.deleteRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: `tags/${tag}`,
                })
              } catch (e) {
                // tag may not exist; ignore
                console.log('Tag deletion skipped or failed (may not exist):', e.message)
              }
            } catch (error) {
              console.log('Error while deleting existing release/tag:', error.message)
            }

      - name: Create Release and upload PDF
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "latest-korean-build"
          name: "Latest Korean Build"
          body: "최신 PDF 빌드입니다."
          files: book_ko.pdf